### ISSUE TITLE
How can I get the summary of original videos？

### ISSUE THREAD

**Issue by Superlee506** [pcshih/pytorch-FCSN#2]
Thanks for your work.
I want to know how can I get get the summary of a original video~
Any sugesstion would be appreciated.

**Comment by pcshih** [comment]
The model will give you key frame format and you have to change it to key shot format to do evaluation. Please refer to [this paper](https://pdfs.semanticscholar.org/ae84/a78c819e3d60e8de05dbf8b3bc8ff890ba28.pdf?_ga=2.237611456.154741614.1567676789-1046876147.1533556766) for format transformation.

Sorry for the late reply...

**Comment by Superlee506** [comment]
@pcshih Thanks for your response~ It helps me a lot.
