### ISSUE TITLE
The performance on summe dataset is not stable, and can't match your performane.

### ISSUE THREAD

**Issue by Superlee506** [pcshih/pytorch-FCSN#3]
Hi, @pcshih ,
Thanks for your sharing, I clone your code and run train_FCSN_1D_sup/train_FCSN_2D_sup on sumbe dataset, but I can't get the same performance as yours. The final averege fscore is also not stable range from(30%~41%). 

However, the performance on the tvsum dataset is quite high, almost abour 85%(fscore), I don't know how.

Any suggestion would be appreciated.
Thanks.

**Comment by pcshih** [comment]
The evaluation method of video summarization is quite weird.

All the fscore you get is based on your luck.

Please refer to [this paper](http://openaccess.thecvf.com/content_CVPR_2019/papers/Otani_Rethinking_the_Evaluation_of_Video_Summaries_CVPR_2019_paper.pdf)

**Comment by Superlee506** [comment]
@pcshih So, the related papers of high performance may be not unbelievable or by chance?

**Comment by pcshih** [comment]
Yes, you can see that the paper I post yesterday. That paper mention that they do 100 times random data and the performance is even better than the trained model...
